# Generated by Django 6.0.2 on 2026-05-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('None', 'None'), ('Market Seller', 'Marketseller'), ('Event Organizer', 'Eventorganizer'), ('Book Contributor', 'Bookcontributor'), ('Project Creator', 'Projectcreator'), ('Commission Maker', 'Commissionmaker')], default='None', max_length=50),
        ),
    ]
